apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: 2023-11-06T16:41:19.000Z
  generation: 2
  labels:
    EntandoKeycloakServer: default-sso-in-namespace
    entando.org/capability: Sso
    entando.org/capability-provision-scope: Namespace
    entando.org/deployment: default-sso-in-namespace
    entando.org/entando-resource-kind: EntandoKeycloakServer
    entando.org/entando-resource-namespace: test-rfadda
  name: default-sso-in-namespace-deployment
  namespace: test-rfadda
  ownerReferences:
    - apiVersion: entando.org/v1
      blockOwnerDeletion: true
      controller: true
      kind: EntandoKeycloakServer
      name: default-sso-in-namespace
      uid: afaf99ab-f89c-43f2-b1a7-9cc356610717
  uid: 1e8ac954-80ab-4f76-8c5c-acd02ae3c5a4
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      EntandoKeycloakServer: default-sso-in-namespace
      entando.org/capability: Sso
      entando.org/capability-provision-scope: Namespace
      entando.org/deployment: default-sso-in-namespace
      entando.org/entando-resource-kind: EntandoKeycloakServer
      entando.org/entando-resource-namespace: test-rfadda
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        EntandoKeycloakServer: default-sso-in-namespace
        entando.org/capability: Sso
        entando.org/capability-provision-scope: Namespace
        entando.org/deployment: default-sso-in-namespace
        entando.org/entando-resource-kind: EntandoKeycloakServer
        entando.org/entando-resource-namespace: test-rfadda
      name: default-sso-in-namespace-pod
    spec:
      containers:
        - env:
            - name: DB_ADDR
              value: >-
                default-postgresql-dbms-in-namespace-service.test-rfadda.svc.cluster.local
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: default-sso-in-namespace-db-secret
                  optional: false
            - name: DB_VENDOR
              value: postgres
            - name: DB_DATABASE
              value: default_postgresql_dbms_in_namespace_db
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  key: username
                  name: default-sso-in-namespace-db-secret
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: default-sso-in-namespace-db-secret
                  optional: false
            - name: JDBC_PARAMS
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /auth
            - name: CONNECTION_CONFIG_ROOT
              value: /etc/entando/secrets
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: default-sso-in-namespace-admin-secret
                  optional: false
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: default-sso-in-namespace-admin-secret
                  optional: false
            - name: PROXY_ADDRESS_FORWARDING
              value: 'true'
          image: registry.hub.docker.com/entando/entando-keycloak:7.2.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /auth
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: server-container
          ports:
            - containerPort: 8080
              name: server-port
              protocol: TCP
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /auth
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: '1'
              memory: 1200Mi
            requests:
              cpu: 250m
              memory: 300Mi
          startupProbe:
            failureThreshold: 11
            httpGet:
              path: /auth
              port: 8080
              scheme: HTTP
            periodSeconds: 36
            successThreshold: 1
            timeoutSeconds: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/jboss/keycloak/standalone/data
              name: default-sso-in-namespace-server-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: default-sso-in-namespace-server-volume
          persistentVolumeClaim:
            claimName: default-sso-in-namespace-server-pvc
status:
  conditions:
    - lastTransitionTime: 2023-11-06T16:43:26.000Z
      lastUpdateTime: 2023-11-06T16:43:26.000Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: 2023-11-06T16:41:19.000Z
      lastUpdateTime: 2023-11-06T16:43:26.000Z
      message: >-
        ReplicaSet "default-sso-in-namespace-deployment-c76d7896c" has
        successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 2
